import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Telemetry processing rules and compliance with NDPR and GDPR.',
};

export default function PrivacyPage() {
  return (
    <main className="max-w-4xl mx-auto py-12 px-6 text-slate-300 text-sm leading-relaxed">
      <Link href="/" className="text-xs text-indigo-400 hover:underline mb-6 inline-block font-mono">
        ← Return to Analytics Dashboard
      </Link>
      <h1 className="text-3xl font-extrabold text-white mb-2">Privacy & Telemetry Processing Policy</h1>
      <p className="text-xs font-mono text-slate-400 mb-8">Effective: September 19, 2026</p>

      <section className="space-y-6">
        <div>
          <h2 className="text-lg font-bold text-white mb-2">1. Ingestion of Network Telemetry</h2>
          <p>
            GeoPersona Analytics ingests IP addresses solely for ephemeral geographic mapping. In accordance with the Nigeria Data Protection Act (NDPA) and GDPR, IP addresses are treated as online identifiers and are not permanently logged to relational databases.
          </p>
        </div>
        <div>
          <h2 className="text-lg font-bold text-white mb-2">2. Synthetic Demographic Data</h2>
          <p>
            Outputs generated by this engine (occupations, child counts, car models, and income brackets) represent statistical synthetic clusters and do not constitute actual data of specific identifiable individuals.
          </p>
        </div>
      </section>
    </main>
  );
}